package com.example.opencodeclient.ui.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb

enum class ThemePreset(val id: String) {
    DEFAULT("default"),
    GITHUB("github"),
    TOKYO_NIGHT("tokyo_night"),
    DRACULA("dracula"),
    NORD("nord"),
    ONE_DARK("one_dark"),
    SOLARIZED("solarized"),
    GRUVBOX("gruvbox"),
    CATPPUCCIN("catppuccin"),
    CHINA_RED("china_red"),
    PERSIMMON("persimmon"),
    LEMON("lemon"),
    FOREST("forest"),
    MINT("mint"),
    SKY_BLUE("sky_blue"),
    GRAPE("grape"),
    CUSTOM("custom"),
}

val PresetDarkSchemes = mapOf(
    ThemePreset.DEFAULT to darkColorScheme(
        primary = Color(0xFF7AA2F7),
        onPrimary = Color(0xFF0D1117),
        primaryContainer = Color(0xFF1F3A5F),
        onPrimaryContainer = Color(0xFFC9D1D9),
        secondary = Color(0xFF7EE787),
        onSecondary = Color(0xFF0D1117),
        background = Color(0xFF0D1117),
        onBackground = Color(0xFFC9D1D9),
        surface = Color(0xFF161B22),
        onSurface = Color(0xFFC9D1D9),
        surfaceVariant = Color(0xFF21262D),
        onSurfaceVariant = Color(0xFF8B949E),
        error = Color(0xFFF85149),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFF3D1214),
        onErrorContainer = Color(0xFFF85149),
        outline = Color(0xFF30363D),
    ),
    ThemePreset.GITHUB to darkColorScheme(
        primary = Color(0xFF58A6FF),
        onPrimary = Color(0xFF0D1117),
        primaryContainer = Color(0xFF1F3A5F),
        onPrimaryContainer = Color(0xFFC9D1D9),
        secondary = Color(0xFF3FB950),
        onSecondary = Color(0xFF0D1117),
        background = Color(0xFF0D1117),
        onBackground = Color(0xFFC9D1D9),
        surface = Color(0xFF161B22),
        onSurface = Color(0xFFC9D1D9),
        surfaceVariant = Color(0xFF21262D),
        onSurfaceVariant = Color(0xFF8B949E),
        error = Color(0xFFF85149),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFF3D1214),
        onErrorContainer = Color(0xFFF85149),
        outline = Color(0xFF30363D),
    ),
    ThemePreset.TOKYO_NIGHT to darkColorScheme(
        primary = Color(0xFF7AA2F7),
        onPrimary = Color(0xFF1A1B26),
        primaryContainer = Color(0xFF24283B),
        onPrimaryContainer = Color(0xFFC0CAF5),
        secondary = Color(0xFF9ECE6A),
        onSecondary = Color(0xFF1A1B26),
        background = Color(0xFF1A1B26),
        onBackground = Color(0xFFC0CAF5),
        surface = Color(0xFF24283B),
        onSurface = Color(0xFFC0CAF5),
        surfaceVariant = Color(0xFF414868),
        onSurfaceVariant = Color(0xFFA9B1D6),
        error = Color(0xFFF7768E),
        onError = Color(0xFF1A1B26),
        errorContainer = Color(0xFF3B2033),
        onErrorContainer = Color(0xFFF7768E),
        outline = Color(0xFF565F89),
    ),
    ThemePreset.DRACULA to darkColorScheme(
        primary = Color(0xFFFFB86C),
        onPrimary = Color(0xFF282A36),
        primaryContainer = Color(0xFF44475A),
        onPrimaryContainer = Color(0xFFF8F8F2),
        secondary = Color(0xFF50FA7B),
        onSecondary = Color(0xFF282A36),
        background = Color(0xFF282A36),
        onBackground = Color(0xFFF8F8F2),
        surface = Color(0xFF21222C),
        onSurface = Color(0xFFF8F8F2),
        surfaceVariant = Color(0xFF44475A),
        onSurfaceVariant = Color(0xFFBFBFBF),
        error = Color(0xFFFF5555),
        onError = Color(0xFF282A36),
        errorContainer = Color(0xFF3D2020),
        onErrorContainer = Color(0xFFFF5555),
        outline = Color(0xFF6272A4),
    ),
    ThemePreset.NORD to darkColorScheme(
        primary = Color(0xFF88C0D0),
        onPrimary = Color(0xFF2E3440),
        primaryContainer = Color(0xFF3B4252),
        onPrimaryContainer = Color(0xFFECEFF4),
        secondary = Color(0xFFA3BE8C),
        onSecondary = Color(0xFF2E3440),
        background = Color(0xFF2E3440),
        onBackground = Color(0xFFECEFF4),
        surface = Color(0xFF3B4252),
        onSurface = Color(0xFFECEFF4),
        surfaceVariant = Color(0xFF434C5E),
        onSurfaceVariant = Color(0xFFD8DEE9),
        error = Color(0xFFBF616A),
        onError = Color(0xFF2E3440),
        errorContainer = Color(0xFF3D2828),
        onErrorContainer = Color(0xFFBF616A),
        outline = Color(0xFF4C566A),
    ),
    ThemePreset.ONE_DARK to darkColorScheme(
        primary = Color(0xFF61AFEF),
        onPrimary = Color(0xFF0F1420),
        primaryContainer = Color(0xFF2C3442),
        onPrimaryContainer = Color(0xFFBBC2CF),
        secondary = Color(0xFF98C379),
        onSecondary = Color(0xFF0F1420),
        background = Color(0xFF282C34),
        onBackground = Color(0xFFBBC2CF),
        surface = Color(0xFF21252B),
        onSurface = Color(0xFFBBC2CF),
        surfaceVariant = Color(0xFF2C313A),
        onSurfaceVariant = Color(0xFF7F8A98),
        error = Color(0xFFE06C75),
        onError = Color(0xFF0F1420),
        errorContainer = Color(0xFF3B2426),
        onErrorContainer = Color(0xFFE06C75),
        outline = Color(0xFF3E4451),
    ),
    ThemePreset.SOLARIZED to darkColorScheme(
        primary = Color(0xFF268BD2),
        onPrimary = Color(0xFF002B36),
        primaryContainer = Color(0xFF073642),
        onPrimaryContainer = Color(0xFF93A1A1),
        secondary = Color(0xFF2AA198),
        onSecondary = Color(0xFF002B36),
        background = Color(0xFF002B36),
        onBackground = Color(0xFF93A1A1),
        surface = Color(0xFF073642),
        onSurface = Color(0xFF93A1A1),
        surfaceVariant = Color(0xFF0D4450),
        onSurfaceVariant = Color(0xFF839496),
        error = Color(0xFFDC322F),
        onError = Color(0xFF002B36),
        errorContainer = Color(0xFF3B1716),
        onErrorContainer = Color(0xFFDC322F),
        outline = Color(0xFF586E75),
    ),
    ThemePreset.GRUVBOX to darkColorScheme(
        primary = Color(0xFF83A598),
        onPrimary = Color(0xFF1D2021),
        primaryContainer = Color(0xFF3C3836),
        onPrimaryContainer = Color(0xFFEBDBB2),
        secondary = Color(0xFFB8BB26),
        onSecondary = Color(0xFF1D2021),
        background = Color(0xFF282828),
        onBackground = Color(0xFFEBDBB2),
        surface = Color(0xFF1D2021),
        onSurface = Color(0xFFEBDBB2),
        surfaceVariant = Color(0xFF32302F),
        onSurfaceVariant = Color(0xFFA89984),
        error = Color(0xFFFB4934),
        onError = Color(0xFF1D2021),
        errorContainer = Color(0xFF3D211C),
        onErrorContainer = Color(0xFFFB4934),
        outline = Color(0xFF504945),
    ),
    ThemePreset.CATPPUCCIN to darkColorScheme(
        primary = Color(0xFF89B4FA),
        onPrimary = Color(0xFF11111B),
        primaryContainer = Color(0xFF313244),
        onPrimaryContainer = Color(0xFFCDD6F4),
        secondary = Color(0xFFA6E3A1),
        onSecondary = Color(0xFF11111B),
        background = Color(0xFF1E1E2E),
        onBackground = Color(0xFFCDD6F4),
        surface = Color(0xFF181825),
        onSurface = Color(0xFFCDD6F4),
        surfaceVariant = Color(0xFF2A2A3C),
        onSurfaceVariant = Color(0xFF9399B2),
        error = Color(0xFFF38BA8),
        onError = Color(0xFF11111B),
        errorContainer = Color(0xFF3B1E2B),
        onErrorContainer = Color(0xFFF38BA8),
        outline = Color(0xFF45475A),
    ),
    ThemePreset.CHINA_RED to darkColorScheme(
        primary = Color(0xFFE5484D),
        onPrimary = Color(0xFF1A0505),
        primaryContainer = Color(0xFF5A1A1D),
        onPrimaryContainer = Color(0xFFFFD6D6),
        secondary = Color(0xFFFFB4B0),
        onSecondary = Color(0xFF200A0A),
        background = Color(0xFF201A1A),
        onBackground = Color(0xFFF2DADA),
        surface = Color(0xFF241C1C),
        onSurface = Color(0xFFF2DADA),
        surfaceVariant = Color(0xFF3A2A2A),
        onSurfaceVariant = Color(0xFFC8A3A3),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF5A4141),
    ),
    ThemePreset.PERSIMMON to darkColorScheme(
        primary = Color(0xFFFF8A3D),
        onPrimary = Color(0xFF2A1200),
        primaryContainer = Color(0xFF5C2A00),
        onPrimaryContainer = Color(0xFFFFDBC5),
        secondary = Color(0xFFFFC9A0),
        onSecondary = Color(0xFF301505),
        background = Color(0xFF201A15),
        onBackground = Color(0xFFF5E2D7),
        surface = Color(0xFF241D17),
        onSurface = Color(0xFFF5E2D7),
        surfaceVariant = Color(0xFF3B2E24),
        onSurfaceVariant = Color(0xFFCEA98F),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF5C4A3C),
    ),
    ThemePreset.LEMON to darkColorScheme(
        primary = Color(0xFFD9C530),
        onPrimary = Color(0xFF2A2500),
        primaryContainer = Color(0xFF544B00),
        onPrimaryContainer = Color(0xFFFFF2A8),
        secondary = Color(0xFFE6DC8C),
        onSecondary = Color(0xFF2A2500),
        background = Color(0xFF201E16),
        onBackground = Color(0xFFF5F0DA),
        surface = Color(0xFF242116),
        onSurface = Color(0xFFF5F0DA),
        surfaceVariant = Color(0xFF3B3826),
        onSurfaceVariant = Color(0xFFCEC28F),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF5C563F),
    ),
    ThemePreset.FOREST to darkColorScheme(
        primary = Color(0xFF4CAF50),
        onPrimary = Color(0xFF0A1A0B),
        primaryContainer = Color(0xFF1F3D22),
        onPrimaryContainer = Color(0xFFC8F0CB),
        secondary = Color(0xFF8BC48E),
        onSecondary = Color(0xFF0E1F10),
        background = Color(0xFF182118),
        onBackground = Color(0xFFDCECDD),
        surface = Color(0xFF1B251C),
        onSurface = Color(0xFFDCECDD),
        surfaceVariant = Color(0xFF29372B),
        onSurfaceVariant = Color(0xFFA3BCA6),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF4A5C4C),
    ),
    ThemePreset.MINT to darkColorScheme(
        primary = Color(0xFF3EC6B0),
        onPrimary = Color(0xFF00211B),
        primaryContainer = Color(0xFF1C4A41),
        onPrimaryContainer = Color(0xFFB8F2E6),
        secondary = Color(0xFF7FD9C8),
        onSecondary = Color(0xFF0E2A24),
        background = Color(0xFF16201E),
        onBackground = Color(0xFFD8EDE8),
        surface = Color(0xFF192522),
        onSurface = Color(0xFFD8EDE8),
        surfaceVariant = Color(0xFF27403B),
        onSurfaceVariant = Color(0xFFA2BDB6),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF485A55),
    ),
    ThemePreset.SKY_BLUE to darkColorScheme(
        primary = Color(0xFF4FA3E5),
        onPrimary = Color(0xFF071C2E),
        primaryContainer = Color(0xFF1E3F5E),
        onPrimaryContainer = Color(0xFFC6E4FF),
        secondary = Color(0xFF8CC4F7),
        onSecondary = Color(0xFF0E2A42),
        background = Color(0xFF171E26),
        onBackground = Color(0xFFDBE8F5),
        surface = Color(0xFF1A232D),
        onSurface = Color(0xFFDBE8F5),
        surfaceVariant = Color(0xFF2A3A48),
        onSurfaceVariant = Color(0xFFA6BACB),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF4A5E6E),
    ),
    ThemePreset.GRAPE to darkColorScheme(
        primary = Color(0xFFB083E8),
        onPrimary = Color(0xFF1C0F33),
        primaryContainer = Color(0xFF3D2A63),
        onPrimaryContainer = Color(0xFFE4D2FF),
        secondary = Color(0xFFCBA5F5),
        onSecondary = Color(0xFF261149),
        background = Color(0xFF201B29),
        onBackground = Color(0xFFEFE3FA),
        surface = Color(0xFF251E30),
        onSurface = Color(0xFFEFE3FA),
        surfaceVariant = Color(0xFF3B3049),
        onSurfaceVariant = Color(0xFFC0AFC9),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF5E5260),
    ),
)

val PresetLightSchemes = mapOf(
    ThemePreset.DEFAULT to lightColorScheme(
        primary = Color(0xFF1F6FEB),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFFFFFF),
        onBackground = Color(0xFF1F2328),
        surface = Color(0xFFF6F8FA),
        onSurface = Color(0xFF1F2328),
        surfaceVariant = Color(0xFFE8ECEF),
        onSurfaceVariant = Color(0xFF636C76),
    ),
    ThemePreset.GITHUB to lightColorScheme(
        primary = Color(0xFF0969DA),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFFFFFF),
        onBackground = Color(0xFF1F2328),
        surface = Color(0xFFF6F8FA),
        onSurface = Color(0xFF1F2328),
        surfaceVariant = Color(0xFFE8ECEF),
        onSurfaceVariant = Color(0xFF636C76),
    ),
    ThemePreset.TOKYO_NIGHT to lightColorScheme(
        primary = Color(0xFF1A1B26),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFFFFFF),
        onBackground = Color(0xFF1A1B26),
        surface = Color(0xFFF5F5F5),
        onSurface = Color(0xFF1A1B26),
        surfaceVariant = Color(0xFFE8E8E8),
        onSurfaceVariant = Color(0xFF636363),
    ),
    ThemePreset.DRACULA to lightColorScheme(
        primary = Color(0xFFFF79C6),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFFFFFF),
        onBackground = Color(0xFF282A36),
        surface = Color(0xFFF8F8F2),
        onSurface = Color(0xFF282A36),
        surfaceVariant = Color(0xFFE8E8E8),
        onSurfaceVariant = Color(0xFF6272A4),
    ),
    ThemePreset.NORD to lightColorScheme(
        primary = Color(0xFF5E81AC),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFECEFF4),
        onBackground = Color(0xFF2E3440),
        surface = Color(0xFFE5E9F0),
        onSurface = Color(0xFF2E3440),
        surfaceVariant = Color(0xFFD8DEE9),
        onSurfaceVariant = Color(0xFF4C566A),
    ),
    ThemePreset.ONE_DARK to lightColorScheme(
        primary = Color(0xFF2B7DBE),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFFFFFF),
        onBackground = Color(0xFF282C34),
        surface = Color(0xFFF0F2F5),
        onSurface = Color(0xFF282C34),
        surfaceVariant = Color(0xFFE2E6EC),
        onSurfaceVariant = Color(0xFF5C6675),
    ),
    ThemePreset.SOLARIZED to lightColorScheme(
        primary = Color(0xFF268BD2),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFDF6E3),
        onBackground = Color(0xFF586E75),
        surface = Color(0xFFEEE8D5),
        onSurface = Color(0xFF586E75),
        surfaceVariant = Color(0xFFE3DDC9),
        onSurfaceVariant = Color(0xFF657B83),
    ),
    ThemePreset.GRUVBOX to lightColorScheme(
        primary = Color(0xFF458588),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFBF1C7),
        onBackground = Color(0xFF3C3836),
        surface = Color(0xFFF2E5BC),
        onSurface = Color(0xFF3C3836),
        surfaceVariant = Color(0xFFE8DDB4),
        onSurfaceVariant = Color(0xFF665C54),
    ),
    ThemePreset.CATPPUCCIN to lightColorScheme(
        primary = Color(0xFF1E88E5),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFEFF1F5),
        onBackground = Color(0xFF4C4F69),
        surface = Color(0xFFE6E7EF),
        onSurface = Color(0xFF4C4F69),
        surfaceVariant = Color(0xFFDCE0E8),
        onSurfaceVariant = Color(0xFF6C6F85),
    ),
    ThemePreset.CHINA_RED to lightColorScheme(
        primary = Color(0xFFE53935),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFDF7F7),
        onBackground = Color(0xFF3B2020),
        surface = Color(0xFFF7E9E9),
        onSurface = Color(0xFF3B2020),
        surfaceVariant = Color(0xFFEFD6D6),
        onSurfaceVariant = Color(0xFF8A5A5A),
    ),
    ThemePreset.PERSIMMON to lightColorScheme(
        primary = Color(0xFFF57C00),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFFF8F2),
        onBackground = Color(0xFF3D2818),
        surface = Color(0xFFFCEBDD),
        onSurface = Color(0xFF3D2818),
        surfaceVariant = Color(0xFFF3D8C2),
        onSurfaceVariant = Color(0xFF8F6642),
    ),
    ThemePreset.LEMON to lightColorScheme(
        primary = Color(0xFFB8A420),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFFFFF7),
        onBackground = Color(0xFF3C3712),
        surface = Color(0xFFF7F0CE),
        onSurface = Color(0xFF3C3712),
        surfaceVariant = Color(0xFFEDE2AC),
        onSurfaceVariant = Color(0xFF8B8140),
    ),
    ThemePreset.FOREST to lightColorScheme(
        primary = Color(0xFF2E7D32),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFF4FBF4),
        onBackground = Color(0xFF1B3320),
        surface = Color(0xFFE3F0E4),
        onSurface = Color(0xFF1B3320),
        surfaceVariant = Color(0xFFC8E2CC),
        onSurfaceVariant = Color(0xFF4F7A57),
    ),
    ThemePreset.MINT to lightColorScheme(
        primary = Color(0xFF00A896),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFF2FBFA),
        onBackground = Color(0xFF16332F),
        surface = Color(0xFFDFF2EE),
        onSurface = Color(0xFF16332F),
        surfaceVariant = Color(0xFFBFE4DE),
        onSurfaceVariant = Color(0xFF3F7266),
    ),
    ThemePreset.SKY_BLUE to lightColorScheme(
        primary = Color(0xFF1E88E5),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFF3F9FF),
        onBackground = Color(0xFF173047),
        surface = Color(0xFFE0EEFA),
        onSurface = Color(0xFF173047),
        surfaceVariant = Color(0xFFC5DEF4),
        onSurfaceVariant = Color(0xFF466681),
    ),
    ThemePreset.GRAPE to lightColorScheme(
        primary = Color(0xFF7B4FC4),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFBF7FF),
        onBackground = Color(0xFF2E2040),
        surface = Color(0xFFEEE2FA),
        onSurface = Color(0xFF2E2040),
        surfaceVariant = Color(0xFFDCC8F2),
        onSurfaceVariant = Color(0xFF7A5E9C),
    ),
)

fun buildCustomScheme(dark: Boolean, colors: Map<String, Long>): ColorScheme {
    val base = if (dark) PresetDarkSchemes[ThemePreset.DEFAULT]!! else PresetLightSchemes[ThemePreset.DEFAULT]!!
    return base.copy(
        primary = Color(colors["primary"] ?: base.primary.toArgb().toLong() and 0xFFFFFFFFL),
        onPrimary = Color(colors["onPrimary"] ?: base.onPrimary.toArgb().toLong() and 0xFFFFFFFFL),
        background = Color(colors["background"] ?: base.background.toArgb().toLong() and 0xFFFFFFFFL),
        onBackground = Color(colors["onBackground"] ?: base.onBackground.toArgb().toLong() and 0xFFFFFFFFL),
        surface = Color(colors["surface"] ?: base.surface.toArgb().toLong() and 0xFFFFFFFFL),
        onSurface = Color(colors["onSurface"] ?: base.onSurface.toArgb().toLong() and 0xFFFFFFFFL),
        surfaceVariant = Color(colors["surfaceVariant"] ?: base.surfaceVariant.toArgb().toLong() and 0xFFFFFFFFL),
        onSurfaceVariant = Color(colors["onSurfaceVariant"] ?: base.onSurfaceVariant.toArgb().toLong() and 0xFFFFFFFFL),
    )
}

@Composable
fun OpenCodeTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    preset: ThemePreset = ThemePreset.DEFAULT,
    customColors: Map<String, Long> = emptyMap(),
    content: @Composable () -> Unit,
) {
    val colors = when (preset) {
        ThemePreset.CUSTOM -> buildCustomScheme(darkTheme, customColors)
        else -> {
            val schemes = if (darkTheme) PresetDarkSchemes else PresetLightSchemes
            schemes[preset] ?: schemes[ThemePreset.DEFAULT]!!
        }
    }
    MaterialTheme(
        colorScheme = colors,
        content = content,
    )
}
