package com.example.opencodeclient.ui.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb

enum class ThemePreset(val id: String) {
    DEFAULT("default"),
    GITHUB("github"),
    TOKYO_NIGHT("tokyo_night"),
    DRACULA("dracula"),
    NORD("nord"),
    ONE_DARK("one_dark"),
    SOLARIZED("solarized"),
    GRUVBOX("gruvbox"),
    CATPPUCCIN("catppuccin"),
    CUSTOM("custom"),
}

val PresetDarkSchemes = mapOf(
    ThemePreset.DEFAULT to darkColorScheme(
        primary = Color(0xFF7AA2F7),
        onPrimary = Color(0xFF0D1117),
        primaryContainer = Color(0xFF1F3A5F),
        onPrimaryContainer = Color(0xFFC9D1D9),
        secondary = Color(0xFF7EE787),
        onSecondary = Color(0xFF0D1117),
        background = Color(0xFF0D1117),
        onBackground = Color(0xFFC9D1D9),
        surface = Color(0xFF161B22),
        onSurface = Color(0xFFC9D1D9),
        surfaceVariant = Color(0xFF21262D),
        onSurfaceVariant = Color(0xFF8B949E),
        error = Color(0xFFF85149),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFF3D1214),
        onErrorContainer = Color(0xFFF85149),
        outline = Color(0xFF30363D),
    ),
    ThemePreset.GITHUB to darkColorScheme(
        primary = Color(0xFF58A6FF),
        onPrimary = Color(0xFF0D1117),
        primaryContainer = Color(0xFF1F3A5F),
        onPrimaryContainer = Color(0xFFC9D1D9),
        secondary = Color(0xFF3FB950),
        onSecondary = Color(0xFF0D1117),
        background = Color(0xFF0D1117),
        onBackground = Color(0xFFC9D1D9),
        surface = Color(0xFF161B22),
        onSurface = Color(0xFFC9D1D9),
        surfaceVariant = Color(0xFF21262D),
        onSurfaceVariant = Color(0xFF8B949E),
        error = Color(0xFFF85149),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFF3D1214),
        onErrorContainer = Color(0xFFF85149),
        outline = Color(0xFF30363D),
    ),
    ThemePreset.TOKYO_NIGHT to darkColorScheme(
        primary = Color(0xFF7AA2F7),
        onPrimary = Color(0xFF1A1B26),
        primaryContainer = Color(0xFF24283B),
        onPrimaryContainer = Color(0xFFC0CAF5),
        secondary = Color(0xFF9ECE6A),
        onSecondary = Color(0xFF1A1B26),
        background = Color(0xFF1A1B26),
        onBackground = Color(0xFFC0CAF5),
        surface = Color(0xFF24283B),
        onSurface = Color(0xFFC0CAF5),
        surfaceVariant = Color(0xFF414868),
        onSurfaceVariant = Color(0xFFA9B1D6),
        error = Color(0xFFF7768E),
        onError = Color(0xFF1A1B26),
        errorContainer = Color(0xFF3B2033),
        onErrorContainer = Color(0xFFF7768E),
        outline = Color(0xFF565F89),
    ),
    ThemePreset.DRACULA to darkColorScheme(
        primary = Color(0xFFFFB86C),
        onPrimary = Color(0xFF282A36),
        primaryContainer = Color(0xFF44475A),
        onPrimaryContainer = Color(0xFFF8F8F2),
        secondary = Color(0xFF50FA7B),
        onSecondary = Color(0xFF282A36),
        background = Color(0xFF282A36),
        onBackground = Color(0xFFF8F8F2),
        surface = Color(0xFF21222C),
        onSurface = Color(0xFFF8F8F2),
        surfaceVariant = Color(0xFF44475A),
        onSurfaceVariant = Color(0xFFBFBFBF),
        error = Color(0xFFFF5555),
        onError = Color(0xFF282A36),
        errorContainer = Color(0xFF3D2020),
        onErrorContainer = Color(0xFFFF5555),
        outline = Color(0xFF6272A4),
    ),
    ThemePreset.NORD to darkColorScheme(
        primary = Color(0xFF88C0D0),
        onPrimary = Color(0xFF2E3440),
        primaryContainer = Color(0xFF3B4252),
        onPrimaryContainer = Color(0xFFECEFF4),
        secondary = Color(0xFFA3BE8C),
        onSecondary = Color(0xFF2E3440),
        background = Color(0xFF2E3440),
        onBackground = Color(0xFFECEFF4),
        surface = Color(0xFF3B4252),
        onSurface = Color(0xFFECEFF4),
        surfaceVariant = Color(0xFF434C5E),
        onSurfaceVariant = Color(0xFFD8DEE9),
        error = Color(0xFFBF616A),
        onError = Color(0xFF2E3440),
        errorContainer = Color(0xFF3D2828),
        onErrorContainer = Color(0xFFBF616A),
        outline = Color(0xFF4C566A),
    ),
    ThemePreset.ONE_DARK to darkColorScheme(
        primary = Color(0xFF61AFEF),
        onPrimary = Color(0xFF0F1420),
        primaryContainer = Color(0xFF2C3442),
        onPrimaryContainer = Color(0xFFBBC2CF),
        secondary = Color(0xFF98C379),
        onSecondary = Color(0xFF0F1420),
        background = Color(0xFF282C34),
        onBackground = Color(0xFFBBC2CF),
        surface = Color(0xFF21252B),
        onSurface = Color(0xFFBBC2CF),
        surfaceVariant = Color(0xFF2C313A),
        onSurfaceVariant = Color(0xFF7F8A98),
        error = Color(0xFFE06C75),
        onError = Color(0xFF0F1420),
        errorContainer = Color(0xFF3B2426),
        onErrorContainer = Color(0xFFE06C75),
        outline = Color(0xFF3E4451),
    ),
    ThemePreset.SOLARIZED to darkColorScheme(
        primary = Color(0xFF268BD2),
        onPrimary = Color(0xFF002B36),
        primaryContainer = Color(0xFF073642),
        onPrimaryContainer = Color(0xFF93A1A1),
        secondary = Color(0xFF2AA198),
        onSecondary = Color(0xFF002B36),
        background = Color(0xFF002B36),
        onBackground = Color(0xFF93A1A1),
        surface = Color(0xFF073642),
        onSurface = Color(0xFF93A1A1),
        surfaceVariant = Color(0xFF0D4450),
        onSurfaceVariant = Color(0xFF839496),
        error = Color(0xFFDC322F),
        onError = Color(0xFF002B36),
        errorContainer = Color(0xFF3B1716),
        onErrorContainer = Color(0xFFDC322F),
        outline = Color(0xFF586E75),
    ),
    ThemePreset.GRUVBOX to darkColorScheme(
        primary = Color(0xFF83A598),
        onPrimary = Color(0xFF1D2021),
        primaryContainer = Color(0xFF3C3836),
        onPrimaryContainer = Color(0xFFEBDBB2),
        secondary = Color(0xFFB8BB26),
        onSecondary = Color(0xFF1D2021),
        background = Color(0xFF282828),
        onBackground = Color(0xFFEBDBB2),
        surface = Color(0xFF1D2021),
        onSurface = Color(0xFFEBDBB2),
        surfaceVariant = Color(0xFF32302F),
        onSurfaceVariant = Color(0xFFA89984),
        error = Color(0xFFFB4934),
        onError = Color(0xFF1D2021),
        errorContainer = Color(0xFF3D211C),
        onErrorContainer = Color(0xFFFB4934),
        outline = Color(0xFF504945),
    ),
    ThemePreset.CATPPUCCIN to darkColorScheme(
        primary = Color(0xFF89B4FA),
        onPrimary = Color(0xFF11111B),
        primaryContainer = Color(0xFF313244),
        onPrimaryContainer = Color(0xFFCDD6F4),
        secondary = Color(0xFFA6E3A1),
        onSecondary = Color(0xFF11111B),
        background = Color(0xFF1E1E2E),
        onBackground = Color(0xFFCDD6F4),
        surface = Color(0xFF181825),
        onSurface = Color(0xFFCDD6F4),
        surfaceVariant = Color(0xFF2A2A3C),
        onSurfaceVariant = Color(0xFF9399B2),
        error = Color(0xFFF38BA8),
        onError = Color(0xFF11111B),
        errorContainer = Color(0xFF3B1E2B),
        onErrorContainer = Color(0xFFF38BA8),
        outline = Color(0xFF45475A),
    ),
)

val PresetLightSchemes = mapOf(
    ThemePreset.DEFAULT to lightColorScheme(
        primary = Color(0xFF1F6FEB),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFFFFFF),
        onBackground = Color(0xFF1F2328),
        surface = Color(0xFFF6F8FA),
        onSurface = Color(0xFF1F2328),
        surfaceVariant = Color(0xFFE8ECEF),
        onSurfaceVariant = Color(0xFF636C76),
    ),
    ThemePreset.GITHUB to lightColorScheme(
        primary = Color(0xFF0969DA),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFFFFFF),
        onBackground = Color(0xFF1F2328),
        surface = Color(0xFFF6F8FA),
        onSurface = Color(0xFF1F2328),
        surfaceVariant = Color(0xFFE8ECEF),
        onSurfaceVariant = Color(0xFF636C76),
    ),
    ThemePreset.TOKYO_NIGHT to lightColorScheme(
        primary = Color(0xFF1A1B26),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFFFFFF),
        onBackground = Color(0xFF1A1B26),
        surface = Color(0xFFF5F5F5),
        onSurface = Color(0xFF1A1B26),
        surfaceVariant = Color(0xFFE8E8E8),
        onSurfaceVariant = Color(0xFF636363),
    ),
    ThemePreset.DRACULA to lightColorScheme(
        primary = Color(0xFFFF79C6),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFFFFFF),
        onBackground = Color(0xFF282A36),
        surface = Color(0xFFF8F8F2),
        onSurface = Color(0xFF282A36),
        surfaceVariant = Color(0xFFE8E8E8),
        onSurfaceVariant = Color(0xFF6272A4),
    ),
    ThemePreset.NORD to lightColorScheme(
        primary = Color(0xFF5E81AC),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFECEFF4),
        onBackground = Color(0xFF2E3440),
        surface = Color(0xFFE5E9F0),
        onSurface = Color(0xFF2E3440),
        surfaceVariant = Color(0xFFD8DEE9),
        onSurfaceVariant = Color(0xFF4C566A),
    ),
    ThemePreset.ONE_DARK to lightColorScheme(
        primary = Color(0xFF2B7DBE),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFFFFFF),
        onBackground = Color(0xFF282C34),
        surface = Color(0xFFF0F2F5),
        onSurface = Color(0xFF282C34),
        surfaceVariant = Color(0xFFE2E6EC),
        onSurfaceVariant = Color(0xFF5C6675),
    ),
    ThemePreset.SOLARIZED to lightColorScheme(
        primary = Color(0xFF268BD2),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFDF6E3),
        onBackground = Color(0xFF586E75),
        surface = Color(0xFFEEE8D5),
        onSurface = Color(0xFF586E75),
        surfaceVariant = Color(0xFFE3DDC9),
        onSurfaceVariant = Color(0xFF657B83),
    ),
    ThemePreset.GRUVBOX to lightColorScheme(
        primary = Color(0xFF458588),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFFBF1C7),
        onBackground = Color(0xFF3C3836),
        surface = Color(0xFFF2E5BC),
        onSurface = Color(0xFF3C3836),
        surfaceVariant = Color(0xFFE8DDB4),
        onSurfaceVariant = Color(0xFF665C54),
    ),
    ThemePreset.CATPPUCCIN to lightColorScheme(
        primary = Color(0xFF1E88E5),
        onPrimary = Color(0xFFFFFFFF),
        background = Color(0xFFEFF1F5),
        onBackground = Color(0xFF4C4F69),
        surface = Color(0xFFE6E7EF),
        onSurface = Color(0xFF4C4F69),
        surfaceVariant = Color(0xFFDCE0E8),
        onSurfaceVariant = Color(0xFF6C6F85),
    ),
)

fun buildCustomScheme(dark: Boolean, colors: Map<String, Long>): ColorScheme {
    val base = if (dark) PresetDarkSchemes[ThemePreset.DEFAULT]!! else PresetLightSchemes[ThemePreset.DEFAULT]!!
    return base.copy(
        primary = Color(colors["primary"] ?: base.primary.toArgb().toLong() and 0xFFFFFFFFL),
        onPrimary = Color(colors["onPrimary"] ?: base.onPrimary.toArgb().toLong() and 0xFFFFFFFFL),
        background = Color(colors["background"] ?: base.background.toArgb().toLong() and 0xFFFFFFFFL),
        onBackground = Color(colors["onBackground"] ?: base.onBackground.toArgb().toLong() and 0xFFFFFFFFL),
        surface = Color(colors["surface"] ?: base.surface.toArgb().toLong() and 0xFFFFFFFFL),
        onSurface = Color(colors["onSurface"] ?: base.onSurface.toArgb().toLong() and 0xFFFFFFFFL),
        surfaceVariant = Color(colors["surfaceVariant"] ?: base.surfaceVariant.toArgb().toLong() and 0xFFFFFFFFL),
        onSurfaceVariant = Color(colors["onSurfaceVariant"] ?: base.onSurfaceVariant.toArgb().toLong() and 0xFFFFFFFFL),
    )
}

@Composable
fun OpenCodeTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    preset: ThemePreset = ThemePreset.DEFAULT,
    customColors: Map<String, Long> = emptyMap(),
    content: @Composable () -> Unit,
) {
    val colors = when (preset) {
        ThemePreset.CUSTOM -> buildCustomScheme(darkTheme, customColors)
        else -> {
            val schemes = if (darkTheme) PresetDarkSchemes else PresetLightSchemes
            schemes[preset] ?: schemes[ThemePreset.DEFAULT]!!
        }
    }
    MaterialTheme(
        colorScheme = colors,
        content = content,
    )
}
